/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAsistenciaRouteImport } from './routes/_authenticated/asistencia'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedCampanasRouteImport } from './routes/_authenticated/campanas'
import { Route as AuthenticatedCentrosCostoRouteImport } from './routes/_authenticated/centros-costo'
import { Route as AuthenticatedDatosRouteImport } from './routes/_authenticated/datos'
import { Route as AuthenticatedDispositivosRouteImport } from './routes/_authenticated/dispositivos'
import { Route as AuthenticatedEmpleadoresRouteImport } from './routes/_authenticated/empleadores'
import { Route as AuthenticatedEmpleadosRouteImport } from './routes/_authenticated/empleados'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedFestivosRouteImport } from './routes/_authenticated/festivos'
import { Route as AuthenticatedImportacionesRouteImport } from './routes/_authenticated/importaciones'
import { Route as AuthenticatedJornadaRouteImport } from './routes/_authenticated/jornada'
import { Route as AuthenticatedMarcacionesRouteImport } from './routes/_authenticated/marcaciones'
import { Route as AuthenticatedNotificacionesRouteImport } from './routes/_authenticated/notificaciones'
import { Route as AuthenticatedNovedadesRouteImport } from './routes/_authenticated/novedades'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedReglasRouteImport } from './routes/_authenticated/reglas'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedResultadosRouteImport } from './routes/_authenticated/resultados'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedTurnosRouteImport } from './routes/_authenticated/turnos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAsistenciaRoute = AuthenticatedAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampanasRoute = AuthenticatedCampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentrosCostoRoute =
  AuthenticatedCentrosCostoRouteImport.update({
    id: '/centros-costo',
    path: '/centros-costo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatosRoute = AuthenticatedDatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispositivosRoute =
  AuthenticatedDispositivosRouteImport.update({
    id: '/dispositivos',
    path: '/dispositivos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpleadoresRoute =
  AuthenticatedEmpleadoresRouteImport.update({
    id: '/empleadores',
    path: '/empleadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpleadosRoute = AuthenticatedEmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFestivosRoute = AuthenticatedFestivosRouteImport.update({
  id: '/festivos',
  path: '/festivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportacionesRoute =
  AuthenticatedImportacionesRouteImport.update({
    id: '/importaciones',
    path: '/importaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJornadaRoute = AuthenticatedJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarcacionesRoute =
  AuthenticatedMarcacionesRouteImport.update({
    id: '/marcaciones',
    path: '/marcaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificacionesRoute =
  AuthenticatedNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovedadesRoute = AuthenticatedNovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReglasRoute = AuthenticatedReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultadosRoute = AuthenticatedResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTurnosRoute = AuthenticatedTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/asistencia': typeof AuthenticatedAsistenciaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/campanas': typeof AuthenticatedCampanasRoute
  '/centros-costo': typeof AuthenticatedCentrosCostoRoute
  '/datos': typeof AuthenticatedDatosRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/empleadores': typeof AuthenticatedEmpleadoresRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/festivos': typeof AuthenticatedFestivosRoute
  '/importaciones': typeof AuthenticatedImportacionesRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/marcaciones': typeof AuthenticatedMarcacionesRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/novedades': typeof AuthenticatedNovedadesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/reglas': typeof AuthenticatedReglasRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/turnos': typeof AuthenticatedTurnosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/asistencia': typeof AuthenticatedAsistenciaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/campanas': typeof AuthenticatedCampanasRoute
  '/centros-costo': typeof AuthenticatedCentrosCostoRoute
  '/datos': typeof AuthenticatedDatosRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/empleadores': typeof AuthenticatedEmpleadoresRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/festivos': typeof AuthenticatedFestivosRoute
  '/importaciones': typeof AuthenticatedImportacionesRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/marcaciones': typeof AuthenticatedMarcacionesRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/novedades': typeof AuthenticatedNovedadesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/reglas': typeof AuthenticatedReglasRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/turnos': typeof AuthenticatedTurnosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/asistencia': typeof AuthenticatedAsistenciaRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/campanas': typeof AuthenticatedCampanasRoute
  '/_authenticated/centros-costo': typeof AuthenticatedCentrosCostoRoute
  '/_authenticated/datos': typeof AuthenticatedDatosRoute
  '/_authenticated/dispositivos': typeof AuthenticatedDispositivosRoute
  '/_authenticated/empleadores': typeof AuthenticatedEmpleadoresRoute
  '/_authenticated/empleados': typeof AuthenticatedEmpleadosRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/festivos': typeof AuthenticatedFestivosRoute
  '/_authenticated/importaciones': typeof AuthenticatedImportacionesRoute
  '/_authenticated/jornada': typeof AuthenticatedJornadaRoute
  '/_authenticated/marcaciones': typeof AuthenticatedMarcacionesRoute
  '/_authenticated/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/_authenticated/novedades': typeof AuthenticatedNovedadesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/reglas': typeof AuthenticatedReglasRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/resultados': typeof AuthenticatedResultadosRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/turnos': typeof AuthenticatedTurnosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/asistencia'
    | '/auditoria'
    | '/campanas'
    | '/centros-costo'
    | '/datos'
    | '/dispositivos'
    | '/empleadores'
    | '/empleados'
    | '/empresas'
    | '/festivos'
    | '/importaciones'
    | '/jornada'
    | '/marcaciones'
    | '/notificaciones'
    | '/novedades'
    | '/panel'
    | '/reglas'
    | '/reportes'
    | '/resultados'
    | '/roles'
    | '/turnos'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/asistencia'
    | '/auditoria'
    | '/campanas'
    | '/centros-costo'
    | '/datos'
    | '/dispositivos'
    | '/empleadores'
    | '/empleados'
    | '/empresas'
    | '/festivos'
    | '/importaciones'
    | '/jornada'
    | '/marcaciones'
    | '/notificaciones'
    | '/novedades'
    | '/panel'
    | '/reglas'
    | '/reportes'
    | '/resultados'
    | '/roles'
    | '/turnos'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/asistencia'
    | '/_authenticated/auditoria'
    | '/_authenticated/campanas'
    | '/_authenticated/centros-costo'
    | '/_authenticated/datos'
    | '/_authenticated/dispositivos'
    | '/_authenticated/empleadores'
    | '/_authenticated/empleados'
    | '/_authenticated/empresas'
    | '/_authenticated/festivos'
    | '/_authenticated/importaciones'
    | '/_authenticated/jornada'
    | '/_authenticated/marcaciones'
    | '/_authenticated/notificaciones'
    | '/_authenticated/novedades'
    | '/_authenticated/panel'
    | '/_authenticated/reglas'
    | '/_authenticated/reportes'
    | '/_authenticated/resultados'
    | '/_authenticated/roles'
    | '/_authenticated/turnos'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/asistencia': {
      id: '/_authenticated/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AuthenticatedAsistenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campanas': {
      id: '/_authenticated/campanas'
      path: '/campanas'
      fullPath: '/campanas'
      preLoaderRoute: typeof AuthenticatedCampanasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-costo': {
      id: '/_authenticated/centros-costo'
      path: '/centros-costo'
      fullPath: '/centros-costo'
      preLoaderRoute: typeof AuthenticatedCentrosCostoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datos': {
      id: '/_authenticated/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof AuthenticatedDatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispositivos': {
      id: '/_authenticated/dispositivos'
      path: '/dispositivos'
      fullPath: '/dispositivos'
      preLoaderRoute: typeof AuthenticatedDispositivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empleadores': {
      id: '/_authenticated/empleadores'
      path: '/empleadores'
      fullPath: '/empleadores'
      preLoaderRoute: typeof AuthenticatedEmpleadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empleados': {
      id: '/_authenticated/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof AuthenticatedEmpleadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festivos': {
      id: '/_authenticated/festivos'
      path: '/festivos'
      fullPath: '/festivos'
      preLoaderRoute: typeof AuthenticatedFestivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importaciones': {
      id: '/_authenticated/importaciones'
      path: '/importaciones'
      fullPath: '/importaciones'
      preLoaderRoute: typeof AuthenticatedImportacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jornada': {
      id: '/_authenticated/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AuthenticatedJornadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marcaciones': {
      id: '/_authenticated/marcaciones'
      path: '/marcaciones'
      fullPath: '/marcaciones'
      preLoaderRoute: typeof AuthenticatedMarcacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificaciones': {
      id: '/_authenticated/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AuthenticatedNotificacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novedades': {
      id: '/_authenticated/novedades'
      path: '/novedades'
      fullPath: '/novedades'
      preLoaderRoute: typeof AuthenticatedNovedadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reglas': {
      id: '/_authenticated/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof AuthenticatedReglasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resultados': {
      id: '/_authenticated/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof AuthenticatedResultadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/turnos': {
      id: '/_authenticated/turnos'
      path: '/turnos'
      fullPath: '/turnos'
      preLoaderRoute: typeof AuthenticatedTurnosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAsistenciaRoute: typeof AuthenticatedAsistenciaRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCampanasRoute: typeof AuthenticatedCampanasRoute
  AuthenticatedCentrosCostoRoute: typeof AuthenticatedCentrosCostoRoute
  AuthenticatedDatosRoute: typeof AuthenticatedDatosRoute
  AuthenticatedDispositivosRoute: typeof AuthenticatedDispositivosRoute
  AuthenticatedEmpleadoresRoute: typeof AuthenticatedEmpleadoresRoute
  AuthenticatedEmpleadosRoute: typeof AuthenticatedEmpleadosRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedFestivosRoute: typeof AuthenticatedFestivosRoute
  AuthenticatedImportacionesRoute: typeof AuthenticatedImportacionesRoute
  AuthenticatedJornadaRoute: typeof AuthenticatedJornadaRoute
  AuthenticatedMarcacionesRoute: typeof AuthenticatedMarcacionesRoute
  AuthenticatedNotificacionesRoute: typeof AuthenticatedNotificacionesRoute
  AuthenticatedNovedadesRoute: typeof AuthenticatedNovedadesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedReglasRoute: typeof AuthenticatedReglasRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedResultadosRoute: typeof AuthenticatedResultadosRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedTurnosRoute: typeof AuthenticatedTurnosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAsistenciaRoute: AuthenticatedAsistenciaRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCampanasRoute: AuthenticatedCampanasRoute,
  AuthenticatedCentrosCostoRoute: AuthenticatedCentrosCostoRoute,
  AuthenticatedDatosRoute: AuthenticatedDatosRoute,
  AuthenticatedDispositivosRoute: AuthenticatedDispositivosRoute,
  AuthenticatedEmpleadoresRoute: AuthenticatedEmpleadoresRoute,
  AuthenticatedEmpleadosRoute: AuthenticatedEmpleadosRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedFestivosRoute: AuthenticatedFestivosRoute,
  AuthenticatedImportacionesRoute: AuthenticatedImportacionesRoute,
  AuthenticatedJornadaRoute: AuthenticatedJornadaRoute,
  AuthenticatedMarcacionesRoute: AuthenticatedMarcacionesRoute,
  AuthenticatedNotificacionesRoute: AuthenticatedNotificacionesRoute,
  AuthenticatedNovedadesRoute: AuthenticatedNovedadesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedReglasRoute: AuthenticatedReglasRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedResultadosRoute: AuthenticatedResultadosRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedTurnosRoute: AuthenticatedTurnosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
